### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 0elena** [cloudwego/biz-demo#41]
Hello:
想问下，咱们这个 [wire](https://github.com/cloudwego/biz-demo/blob/main/bookinfo/internal/server/productpage/wire.go)、wire_gen中的代码是根据啥生成的么？还是一点点手写的？包括ratings、reviews等服务关于wire这块的。请说下，谢谢。

**Comment by li-jin-gou** [comment]
The title can be changed

**Comment by li-jin-gou** [comment]
refer to https://github.com/google/wire and use google search
