### ISSUE TITLE
关于链路跟踪的UI开源

### ISSUE THREAD

**Issue by damon008** [cloudwego/biz-demo#42]
想问下，咱们这个链路跟踪最后的展示UIvstack有开源么？感觉比jaeger展示要好

**Comment by GuangmingLuo** [comment]
@CoderPoet PTAL

**Comment by CoderPoet** [comment]
> 想问下，咱们这个链路跟踪最后的展示UIvstack有开源么？感觉比jaeger展示要好

是 vestack 中的一个子产品哈：https://www.volcengine.com/product/veStack

**Comment by 0elena** [comment]
> 

没有开源版本么？

**Comment by CoderPoet** [comment]
> 

目前暂时还没有，后面可能会陆续有一些观测相关的套件开源出来
