### ISSUE TITLE
biz-demo bookinfo docker image pull failed

### ISSUE THREAD

**Issue by succulentxb** [cloudwego/biz-demo#45]
> $ docker pull cr-cn-beijing.volces.com/cloudwego-demo/bookinfo:v1.0
> Error response from daemon: toomanyrequests: remaining traffic quota is not enough to download this layer for current month

Error when pull cloudwego-demo image, is there a image pull quota limit?

**Comment by li-jin-gou** [comment]
cc @CoderPoet

**Comment by CoderPoet** [comment]
> > $ docker pull cr-cn-beijing.volces.com/cloudwego-demo/bookinfo:v1.0
> > Error response from daemon: toomanyrequests: remaining traffic quota is not enough to download this layer for current month
> 
> Error when pull cloudwego-demo image, is there a image pull quota limit?

Yes, at present, this has a quota limit, you can build the image by yourself first. Later, I migrated the image registry
