### ISSUE TITLE
Typo in the command line for Query note in the ReadMe for EasyNote

### ISSUE THREAD

**Issue by yiwen101** [cloudwego/biz-demo#46]
**Describe the bug**

The command line should be "go run main.go -action queryNote" rather than “ "go run main.go -action queryNoten' "

**To Reproduce**
1. Go to ReadMe of the EasyNote
2. Scroll down to 'Query Note'
3. See error

**Screenshots**
<img width="1114" alt="Screenshot 2023-06-06 at 13 37 23" src="https://github.com/cloudwego/biz-demo/assets/121547057/e54b038a-c896-48e3-8d47-515e2f207f45">

Also, I would deeply appreciate if I could trouble the author to include a few lines in the ReadMe to briefly explain how externals could interact with the EasyNote App, for example, how to use postman to send HTTP request with the right format.

**Comment by li-jin-gou** [comment]
cc @justlorain
