### ISSUE TITLE
Nacos server is not running

### ISSUE THREAD

**Issue by yiwen101** [cloudwego/biz-demo#47]
**Describe the bug**

Could not get the expected output as described in the Readme of the Open-payment-platform when following its instructions precisely

**To Reproduce**

Follow the ReadMe instruction: 
"## How to Run
> root directory is `open-payment-platform`.
#### Prepare

- start docker env with mysql and nacos
```shell
# root directory
make start
```

#### Gateway

- start http gateway
```shell
# root directory
make gateway
```

#### Payment server
> run this server,you should wait for the Nacos server is running.
> How to check the Nacos? you can open the link http://127.0.0.1:8848/nacos/index.html#/login
"
and http://127.0.0.1:8848/nacos/index.html#/login could not be opened

**Expected behavior**

Naco server should be running, so that the payment servers can run

**Screenshots**
Command line output when starting the RPC servers:
<img width="1384" alt="Screenshot 2023-06-06 at 17 53 50" src="https://github.com/cloudwego/biz-demo/assets/121547057/d1b09930-a06a-471c-b95e-1955e3516edb">

Command line output from the HTTP server:
<img width="577" alt="Screenshot 2023-06-06 at 17 52 53" src="https://github.com/cloudwego/biz-demo/assets/121547057/309862bc-cc51-488e-9c76-37da6043917d">

Failure to open the webpage to verify that Nacos server is running:
<img width="1512" alt="Screenshot 2023-06-06 at 17 55 28" src="https://github.com/cloudwego/biz-demo/assets/121547057/620a2cf4-f2ac-47a8-8bda-0828fb628f16">

**Kitex version:**

v0.5.2

**Environment:**

The output of `go env`:
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/wangyiwen/Library/Caches/go-build"
GOENV="/Users/wangyiwen/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/wangyiwen/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/wangyiwen/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/wangyiwen/go/src/open-payment-platform/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ps/hkhsdf0j5ql98hgzk334whzc0000gn/T/go-build2437649674=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Additional context**

The problem persist after running "go get github.com/hertz-contrib/registry/nacos"

**Comment by li-jin-gou** [comment]
cc @baiyutang

**Comment by yiwen101** [comment]
Additional information:
After running "make start" at the root directory, I could see "Container open-payment-platform-nacos-1 running" 
<img width="1381" alt="Screenshot 2023-06-07 at 08 16 36" src="https://github.com/cloudwego/biz-demo/assets/121547057/f729c802-b21b-4abc-8308-233900c3db77">

But I cannot visit the server. The error message on the browser is like:
<img width="870" alt="Screenshot 2023-06-07 at 08 18 49" src="https://github.com/cloudwego/biz-demo/assets/121547057/9478cc9e-ba68-4aa4-aa97-beacdac1a7b1">

**Comment by baiyutang** [comment]
> Additional information: After running "make start" at the root directory, I could see "Container open-payment-platform-nacos-1 running" <img alt="Screenshot 2023-06-07 at 08 16 36" width="1381" src="https://user-images.githubusercontent.com/121547057/243866205-f729c802-b21b-4abc-8308-233900c3db77.png">
> 
> But I cannot visit the server. The error message on the browser is like: <img alt="Screenshot 2023-06-07 at 08 18 49" width="870" src="https://user-images.githubusercontent.com/121547057/243866409-9478cc9e-ba68-4aa4-aa97-beacdac1a7b1.png">

I can not find any problems. Please Recheck the Containers. Such as `docker ps` ,make sure the `open-payment-platform_nacos_1` is running.
![image](https://github.com/cloudwego/biz-demo/assets/10782183/64363a23-4a6d-427d-8e96-0e83364a5200)
![image](https://github.com/cloudwego/biz-demo/assets/10782183/12911565-e9f4-480f-99b7-aa1b172fd46d)

**Comment by yiwen101** [comment]
Thank you for your guidance, I found the issue.

<img width="1246" alt="Screenshot 2023-06-10 at 13 57 15" src="https://github.com/cloudwego/biz-demo/assets/121547057/5311c793-799e-4c81-8e4a-d9fa68585edf">

It seems that the docker image for running the Nacos server is based on AMD chips, while my laptop run on ARM chips, so the server failed.

Thank you for your time
