### ISSUE TITLE
easynote运行user与note一直提示rpc error

### ISSUE THREAD

**Issue by xilin693** [cloudwego/biz-demo#55]
rpc error: code = Unimplemented desc = unknown service opentelemetry.proto.collector.metrics.v1.MetricsService

**Comment by li-jin-gou** [comment]
cc @justlorain

**Comment by li-jin-gou** [comment]
same to https://github.com/jaegertracing/jaeger/issues/2620

**Comment by li-jin-gou** [comment]
cc @Skyenought

**Comment by rogerogers** [comment]
I will fix this.
