### ISSUE TITLE
gomall项目中makefile29-35行疑问

### ISSUE THREAD

**Issue by darrenxyue** [cloudwego/biz-demo#60]
PHONY: gen-checkout-client
gen-checkout-client:
	@cd app/frontend && cwgo client -I ../../idl --type RPC --service checkout --module github.com/cloudwego/biz-demo/gomall/app/frontend --idl ../../idl/checkout.proto

.PHONY: gen-order-client
gen-order-client:
	@cd app/frontend && cwgo client -I ../../idl --type RPC --service order --module github.com/cloudwego/biz-demo/gomall/app/frontend --idl ../../idl/order.proto
前面21-23行已经生成了说有RPC的client，为什么这里还要在frontend里面生成RPC 的client？并且没有看到生成的文件

**Comment by rogerogers** [comment]
这部分是之前遗留的，现在已经不需要了，晚点我来删掉
执行前面的 gen-client 就 OK 了

**Comment by darrenxyue** [comment]
好的

**Comment by darrenxyue** [comment]
前面的还没有删掉，下面图示这里写漏了client
![image](https://github.com/cloudwego/biz-demo/assets/28799116/2f4c94c1-2fca-4edb-b0b5-06f161fca6b0)

**Comment by rogerogers** [comment]
抱歉，最近有点忙， 马上修复
