### ISSUE TITLE
接口错误返回

### ISSUE THREAD

**Issue by darrenxyue** [cloudwego/biz-demo#68]
请问下，接口调用错误后也返回 200，这个前端要怎么处理？
<img width="660" alt="image" src="https://github.com/cloudwego/biz-demo/assets/28799116/5d530105-aaee-45dc-b825-832f2a818336">

**Comment by rogerogers** [comment]
这个我觉得一般会对 utils.SendErrResponse 做下改造
比如

```go
type ErrResponse struct {
	Success  bool
	Code     int
	ErrorMsg string
}

// SendErrResponse  pack error response
func SendErrResponse(ctx context.Context, c *app.RequestContext, code int, err error) {
	// todo edit custom code
	c.JSON(code, ErrResponse{Success: false, ErrorMsg: err.Error()})
}
```
最终调用端根据具体响应处理

**Comment by welkeyever** [comment]
这个错误码没有很好的遵循 HTTP status & RESTful API 规范，正常来说 client 侧不符合预期应该是 4xx 错误吗、服务端处理错误为 5xx，可以参考下

**Comment by darrenxyue** [comment]
> 这个错误码没有很好的遵循 HTTP status & RESTful API 规范，正常来说 client 侧不符合预期应该是 4xx 错误吗、服务端处理错误为 5xx，可以参考下

这个是 cwgo 自动生成的，我的疑问就是这里，按照  HTTP status & RESTful API 规范 来的话前端就能直接处理了，谢谢解答

**Comment by darrenxyue** [comment]
> 这个我觉得一般会对 utils.SendErrResponse 做下改造 比如
> 
> ```go
> type ErrResponse struct {
> 	Success  bool
> 	Code     int
> 	ErrorMsg string
> }
> 
> // SendErrResponse  pack error response
> func SendErrResponse(ctx context.Context, c *app.RequestContext, code int, err error) {
> 	// todo edit custom code
> 	c.JSON(code, ErrResponse{Success: false, ErrorMsg: err.Error()})
> }
> ```
> 
> 最终调用端根据具体响应处理

好勒，谢谢解答

**Comment by GuangmingLuo** [comment]
后续在这个 issue 跟进吧 https://github.com/cloudwego/cwgo/issues/189

**Comment by li-jin-gou** [comment]
@darrenxyue 新增了一个 V2 模版。https://github.com/yuxialuozi/standard_v2/blob/main/biz/handler/hello3/hello_service.go#L20
